name: Tests

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Restore
        working-directory: Day-3
        run: dotnet restore

      - name: Build
        working-directory: Day-3
        run: dotnet build --no-restore

      - name: Unit Tests
        working-directory: Day-3
        run: dotnet test ./Quotes.Tests.Unit --no-build

      - name: Integration Tests
        working-directory: Day-3
        run: dotnet test ./Quotes.Tests.Integration --no-build